### ISSUE TITLE
Unable to select different car on first setup

### ISSUE THREAD

**Issue by volkerrichert** [dbweb-ch/ioBroker.tesla-motors#10]
If you have more than one car connrected to your account, you can't select one form the dropDown. The first one ist shown, but the DD will not open. You have to save an reopen the setup

**Comment by dbweb-ch** [comment]
Fixed in latest commit, but I have only one car, so can you retest?

**Comment by volkerrichert** [comment]
0.2.2 is not available via normal update atm. But I'll retest it

**Comment by dbweb-ch** [comment]
Will release 0.2.2 today and push to latest

**Comment by volkerrichert** [comment]
Thumbs Up!

**Comment by volkerrichert** [comment]
not show, yet. :-) I'll recheck later

**Comment by dbweb-ch** [comment]
ah forgot to mention, afaik npm-list gets updated only once per day. So should be there tomorrow.

**Comment by volkerrichert** [comment]
Yeap, works fine. I can select different vehicles!
