### ISSUE TITLE
Can't use manual Token (Automatic Token still not working)

### ISSUE THREAD

**Issue by ChrisVonFrosta** [dbweb-ch/ioBroker.tesla-motors#102]
Since i red that the automatic token refresh is broken i tried to insert it manually.
i cant safe it.
Answer: (translatet from german) "you have to get a token before you can safe"

i don't use 2fa.
i logs under tesla is "Username or Password invalid. No response"
but i never changed it. it still work on tesla website. and i retyped it in adapter settings.

**Comment by dbweb-ch** [comment]
Did you use the latest version 0.5.4?
You first need zo get vehicle and then if this works, click save.

**Comment by ChrisVonFrosta** [comment]
i have version 0.5.5

if you say "latest version 0.5.4" it seems that i got the newest beta  version.

So i have to check how to downgrade?!
i can't get the vehicle with manually inserted token.

and one more question. what i have to insert for refresh token?

**Comment by ChrisVonFrosta** [comment]
the same with 0.5.4

insert token manually and after click on save i got:
"you have to get a token before you can safe"

**Comment by dbweb-ch** [comment]
The refresh token is the 2nd token you get. It is used to refresh the main token which expires after 45 days

**Comment by ChrisVonFrosta** [comment]
Ok... i got the php script and create token and refresh token... tried with instance from 0.5.5 and 0.5.4.
both not working.
after insert the tokens and click on "get cars", the button becomes grey and nothing happend. No Car is available.
Save is not available "slect a car before save"

**Comment by dbweb-ch** [comment]
Please consider version 1.x under https://github.com/iobroker-community-adapters/ioBroker.tesla-motors
