### ISSUE TITLE
Climate button in 1.0.1?

### ISSUE THREAD

**Issue by aski71** [dbweb-ch/ioBroker.tesla-motors#107]
Hi,
I can't finde the Climate button in 1.0.1 under my vehicles "remote" section anymore.
Where is it? Is it auto-conditioning-start?
Also: Is there an up-to-date legend for all the data points?
Some of the new ones are not really self explanatory, like e.g.:
remote-seat-heater-request-0 to 5 (which seat is which number?)

Thanks,
Alex :-)

**Comment by dbweb-ch** [comment]
You can use documentation on https://tesla-api.timdorr.com/
For the climate, it is auto_conditioning_start and auto_conditioning_stop
Please ask further question under the new github page for the adapter:
https://github.com/iobroker-community-adapters/ioBroker.tesla-motors

**Comment by aski71** [comment]
Thanks. Will do.
