### ISSUE TITLE
adapter does not start, can't get new token

### ISSUE THREAD

**Issue by ChrisPrefect** [dbweb-ch/ioBroker.tesla-motors#11]
I had the adapter set up properly and got some valid values.

But it stopped working a long time ago. When I tried to get a new token, it just says "start adapter first" but it is running, but with a red dot in the adapter list. 

So I can't get a new token and the adapter can't start because maybe the token is wrong.

Here are some logs:
`
tesla-motors.0 | 2020-01-25 18:38:39.503 | info | (22157) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
-- | -- | -- | --
tesla-motors.0 | 2020-01-25 18:38:39.502 | info | (22157) terminating
tesla-motors.0 | 2020-01-25 18:38:38.995 | info | (22157) Got terminate signal TERMINATE_YOURSELF
tesla-motors.0 | 2020-01-25 18:38:38.943 | info | (22157) Setting a new Token, Adapter will reboot after this automatically
tesla-motors.0 | 2020-01-25 18:38:38.164 | warn | (22157) You tried to wake up the car, but there is currently no valid Token, please configure Adapter first!
tesla-motors.0 | 2020-01-25 18:38:38.153 | info | (22157) Try to get a new token
tesla-motors.0 | 2020-01-25 18:38:38.133 | warn | (22157) Could not refresh Token, trying to get a new Token
tesla-motors.0 | 2020-01-25 18:38:38.114 | warn | (22157) Invalid answer from Vehicle request. Error: Unauthorized
tesla-motors.0 | 2020-01-25 18:38:35.856 | info | (22157) starting. Version 0.2.2 in /opt/iobroker/node_modules/iobroker.tesla-motors, node: v8.15.0
`

Thanks!

**Comment by dbweb-ch** [comment]
Oh I see the issue, it can't get a new token and restarts over and over. I
am not able to fix it this week, but uninstall and reinstall should resolve
it for the next 60 days, until then I will have a fix.

ChrisPrefect <notifications@github.com> schrieb am Sa., 25. Jan. 2020,
18:46:

**Comment by dbweb-ch** [comment]
I tried to reproduce this but was not able with current version. Refreshing the token works fine everytime I run it.
I made some changes to make the refresh process more stable. Can you update to the latest github version and check if this happens again?

**Comment by Blacklimo1** [comment]
Hallo dbweb, 
bekomme ebenfalls den Adapter nicht zum starten, Login ist definitiv richtig im log steht

tesla-motors.0 | 2020-02-20 21:48:42.893 | warn | Invalid answer from Vehicle request. Error: Unauthorized

tesla-motors.0 | 2020-02-20 21:48:39.748 | warn | You tried to wake up the car, but there is currently no valid Token, please configure Adapter first!

**Comment by dbweb-ch** [comment]
Hi


Warst du verbunden und bis jetzt nach ein paar Wochen nicht mehr verbunden?
Hast du die aktuellste Version von Adapter?

Blacklimo1 <notifications@github.com> schrieb am Do., 20. Feb. 2020, 21:50:

**Comment by Blacklimo1** [comment]
Hi, habe Version 0.2.2.  Habe den Adapter jetzt erst installiert um mein Model 3 über IoBroker für PV Überschuss laden aufzuwecken.  Nachdem ich den Adapter gestartet habe, habe ich Benutzer und Passwort für den Tesla Account eingegeben und dann auf "Toke holen" geklickt. Dann kommt nur noch der Anmeldefehler im LOG. Habe die Credentials aber wirklich expliziet nochmal kontrolliert. Danke Dir für die wahnsinnig schnelle Antwort Gruss

**Comment by dbweb-ch** [comment]
Also wenn "Token holen" nicht klappt muss es an den Credentials liegen. Ist
normalerweise deine komplette mailadresse und dein Passwort. Loginprobleme
gab es bisher keine.
Der iobroker-Rechner hat Internetzugriff nehme ich an?

Blacklimo1 <notifications@github.com> schrieb am Do., 20. Feb. 2020, 22:52:

**Comment by Blacklimo1** [comment]
Ja habe  habe mich auch Online direkt bei Tesla.com  angemeldet um gegenzuprüfen.  Werden im Adapter vielleicht irgendwelche Sonderezeichen  nicht beachtet!? Muss noch irgendwas anderes außer dein Adapter installiert werden. ? Habe die Credentials im Teslams Node in Node Red probiert, da funktioniert es auch. Ich verzweifle hier noch 
    	
    	

    	
    
  




On Thu, Feb 20, 2020 at 11:15 PM +0100, "Nick" <notifications@github.com> wrote:










Also wenn "Token holen" nicht klappt muss es an den Credentials liegen. Ist


normalerweise deine komplette mailadresse und dein Passwort. Loginprobleme


gab es bisher keine.


Der iobroker-Rechner hat Internetzugriff nehme ich an?





Blacklimo1 <notifications@github.com> schrieb am Do., 20. Feb. 2020, 22:52:

**Comment by NCC-1701S** [comment]
Ich habe den Adapter ganz neu installiert und habe das gleiche Problem. Die Fehlermeldung besagt, dass kein neuer Code generiert werden kann, weil keine Credentials gespeichert sind. Die können aber nicht gespeichert werden, da der Speicher-Button ausgegraut ist. Ich denke das Problem am Adapter ist tatsächlich die Erstinstallation.
Ich habe den Adapter auch mehrfach deinstalliert und neu installiert. Meine Login-Daten stimmen definitiv.

**Comment by dbweb-ch** [comment]
Die Credentials müssen nicht zuerst gespeichert werden, einfach eintragen
und dann auf "Token holen" klicken.
Speichern kannst du erst wenn du ein Token geholt hast.
Dazu muss der Adapter laufen.

Am Di., 25. Feb. 2020 um 14:45 Uhr schrieb NCC-1701S <
notifications@github.com>:

**Comment by NCC-1701S** [comment]
Habe den Adapter laufen und hier ist die Fehlermeldung bei Klick auf "TOKEN HOLEN":

 error: tesla-motors.0 (2301) Your authentification token is not valid or expired. Can't get a new token because you did not store username / password. Please request a new token in Adapter Configuration

**Comment by Blacklimo1** [comment]
Ja genau das ist auch mein Problem

**Comment by NCC-1701S** [comment]
Der Fehler liegt in der main.js Zeile 382 und nachfolgend nach dem if. Ich habe diese nachfolgenden Zeilen mal aaskommentiert und schon funktioniert es:
//            if(Adapter.config.teslaUsername.length == 0 || Adapter.config.teslaPassword.length == 0){
//                Adapter.log.error("Your authentification token is not valid or expired. Can't get a new token because you did not store username / password. Please request a new token in Adapter Configuration");
//                Adapter.sendTo(msg.from, msg.command, {success: false}, msg.callback);
//                return;
//            }

**Comment by dbweb-ch** [comment]
Oh, sorry, wirklich mein Fehler. Da hat die vermeintliche Fehlerbehebung
erst den Fehler ausgelöst. Danke für die Codeanalyse, werd ich morgen
sogleich korrigieren.

NCC-1701S <notifications@github.com> schrieb am Di., 25. Feb. 2020, 20:30:

**Comment by dbweb-ch** [comment]
ist korrigiert.
