### ISSUE TITLE
Tesla token

### ISSUE THREAD

**Issue by ZoltanBrindza** [dbweb-ch/ioBroker.tesla-motors#112]
Hi
I cant connect to a Tesla account,before that it worked but after a while I want to log in again but.....

![Skjermbilde (8)_LI](https://user-images.githubusercontent.com/74625069/136454745-89ca864e-9f61-4d1b-8c42-48f8d32c41a9.jpg)

**Comment by matthiasbrohm** [comment]
Ich habe das gleiche Problem. Leider kann ich manuell auch keinen Token hinzufügen

**Comment by dbweb-ch** [comment]
you need to switch to the new adapter, this one is broken as soon as you need to retrieve a new token.
You can find the new one here:
https://github.com/iobroker-community-adapters/ioBroker.tesla-motors
