### ISSUE TITLE
Adjustable "smart" refresh rate?

### ISSUE THREAD

**Issue by jensb** [dbweb-ch/ioBroker.tesla-motors#16]
With "smart" refresh rate, the car does not wake up unless necessary, which works great.

But once the car is woken up, recording things like speed, energy consumption or location (lat/lng) just once a minute is too little. The Tesla app seems to update the location, speed and remaining charge once a second (!) while the app is opened.

Can we make the "smart" adjustment period configurable, or at least request data more often (maybe every 5s?) - at least while the car is moving?

**Comment by dbweb-ch** [comment]
Yes, was already thinking of this a few times. Will integrate that soon.

jensb <notifications@github.com> schrieb am Do., 5. März 2020, 22:22:

**Comment by dbweb-ch** [comment]
Done in version 0.2.3

**Comment by jensb** [comment]
Perfect, thank you!
How do I get this update into ioBroker?

**Comment by dbweb-ch** [comment]
It is in the latest repo already.

jensb <notifications@github.com> schrieb am Mi., 11. März 2020, 00:12:

**Comment by jensb** [comment]
I see, but it's not offered to me in iobroker as an update. I am on 0.2.2 and no 0.2.3 is offered there. Refreshing the list doesn't help, command line also doesn't find the update.
Maybe I'm overlooking something?

**Comment by dbweb-ch** [comment]
Tesla is installed from Latest, not yet from Stable. Did you change your config to latest? Otherwise you can also update with the "cat" using the github link. Select in the adapter list the "cat"-Symbol (3rd from right), select "beliebig" and use the github link.
