### ISSUE TITLE
mileage

### ISSUE THREAD

**Issue by juchstrasse** [dbweb-ch/ioBroker.tesla-motors#2]
Hello and thanks for the great adapter.
In the Tesla app you can see the mileage of the vehicle data. Can this not be read out for the adapter?
This would be useful for calculations.

**Comment by dbweb-ch** [comment]
Hi,

You mean total mileage? This is in the datapoint tesla-motors.0.vehicle.odometer.
Under tesla-motors.0.chargeState you can also see your range including estimated range based on current conditions.

**Comment by juchstrasse** [comment]
Hi,
Thanks for the feedback.
I see the problem now. With odometers stands with me 8770.055172 km and in the app 14114 km. If I convert the 8770 miles to km, it givs 14114 km. So under odometers the value is given in miles but marked with km. ;)

Sorry: translated with Google

**Comment by dbweb-ch** [comment]
Ok, so there you might found a bug. What have you been setting in your car, miles or km? it should display the same format as the car. And are other values like range displayed correct?

**Comment by juchstrasse** [comment]
I have set km in the car and other values like range displayed correct in km and correct numbers.

**Comment by dbweb-ch** [comment]
ok, pretty strange. Did you ever have set in miles? The values are directly from the car api, either all in km or all in miles. Does it also update when you drive around?

**Comment by juchstrasse** [comment]
No Problem. Im happy you made this adapter.
Out of this case, it works perfectly for me.

**Comment by dbweb-ch** [comment]
Fixed with version 0.2.1

**Comment by juchstrasse** [comment]
Thank you. this works perfect. :)
