### ISSUE TITLE
Could not get token from Tesla

### ISSUE THREAD

**Issue by lingg-ol** [dbweb-ch/ioBroker.tesla-motors#20]
After entering my Tesla account credentials and pressing GET TOKEN an error box is shown saying:
Could not retrieve token, Error from Tesla: authorization_required_for_txid_`f5e32de8bc4793fdddde31398ab3b4ac`

I use adapter version 0.2.3

**Comment by dbweb-ch** [comment]
This means your credentials are wrong, usually.

lingg-ol <notifications@github.com> schrieb am So., 5. Apr. 2020, 18:21:

**Comment by lingg-ol** [comment]
You are completely right. Sorry my mistake
