### ISSUE TITLE
No token refresh if token gets invalidated

### ISSUE THREAD

**Issue by ChrisPrefect** [dbweb-ch/ioBroker.tesla-motors#21]
It seems like the adapter will not request a new token with the saved credentials if the current token gets invalidated from Tesla.

The adapter stopped working some days ago without a notification. 

I had to go to the adapter config and click on get token, then I got an error message "please start adapter first", despite that it was already running. After a restart, I was able to get a new token, without changing the login information.

**Comment by dbweb-ch** [comment]
Yes, I see the same every few month, will try to look into this soon.

**Comment by DanielWeeber** [comment]
Happend to me aswell, but I am unable to get a new token or it is unauthorized immediately afterwards

`

tesla-motors.0 | 2020-05-18 00:01:54.896 | info | (12229) Got terminate signal TERMINATE_YOURSELF
-- | -- | -- | --
tesla-motors.0 | 2020-05-18 00:01:54.872 | info | (12229) Setting a new Token
tesla-motors.0 | 2020-05-18 00:01:54.651 | info | (12229) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
tesla-motors.0 | 2020-05-18 00:01:54.650 | info | (12229) terminating
tesla-motors.0 | 2020-05-18 00:01:54.144 | info | (12229) Got terminate signal TERMINATE_YOURSELF
tesla-motors.0 | 2020-05-18 00:01:53.976 | info | (12229) starting. Version 0.2.3 in /opt/iobroker/node_modules/iobroker.tesla-motors, node: v10.19.0
tesla-motors.0 | 2020-05-18 00:01:46.597 | info | (12205) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
tesla-motors.0 | 2020-05-18 00:01:46.596 | info | (12205) terminating
tesla-motors.0 | 2020-05-18 00:01:46.095 | warn | (12205) You tried to wake up the car, but there is currently no valid Token, please configure Adapter first!
tesla-motors.0 | 2020-05-18 00:01:46.093 | info | (12205) Got terminate signal TERMINATE_YOURSELF
tesla-motors.0 | 2020-05-18 00:01:46.072 | info | (12205) Setting a new Token
tesla-motors.0 | 2020-05-18 00:01:46.063 | warn | (12205) Invalid answer from Vehicle request. Error: Unauthorized
tesla-motors.0 | 2020-05-18 00:01:45.235 | info | (12205) starting. Version 0.2.3 in /opt/iobroker/node_modules/iobroker.tesla-motors, node: v10.19.0
tesla-motors.0 | 2020-05-18 00:01:37.569 | info | (12184) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
tesla-motors.0 | 2020-05-18 00:01:37.567 | info | (12184) terminating
tesla-motors.0 | 2020-05-18 00:01:37.059 | info | (12184) Got terminate signal TERMINATE_YOURSELF
tesla-motors.0 | 2020-05-18 00:01:37.042 | warn | (12184) You tried to wake up the car, but there is currently no valid Token, please configure Adapter first!
tesla-motors.0 | 2020-05-18 00:01:36.694 | info | (12184) Setting a new Token
tesla-motors.0 | 2020-05-18 00:01:36.683 | warn | (12184) Invalid answer from Vehicle request. Error: Unauthorized
tesla-motors.0 | 2020-05-18 00:01:35.721 | info | (12184) starting. Version 0.2.3 in /opt/iobroker/node_modules/iobroker.tesla-motors, node: v10.19.0
tesla-motors.0 | 2020-05-18 00:01:28.736 | info | (12165) Received a new Token
tesla-motors.0 | 2020-05-18 00:01:28.431 | info | (12165) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
tesla-motors.0 | 2020-05-18 00:01:28.430 | info | (12165) terminating
tesla-motors.0 | 2020-05-18 00:01:27.927 | info | (12165) Got terminate signal TERMINATE_YOURSELF
tesla-motors.0 | 2020-05-18 00:01:27.905 | info | (12165) Setting a new Token
tesla-motors.0 | 2020-05-18 00:01:27.631 | info | (12165) Try to get a token
tesla-motors.0 | 2020-05-18 00:01:26.898 | info | (12165) starting. Version 0.2.3 in /opt/iobroker/node_modules/iobroker.tesla-motors, node: v10.19.0
tesla-motors.0 | 2020-05-18 00:01:19.669 | info | (12141) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
tesla-motors.0 | 2020-05-18 00:01:19.668 | info | (12141) terminating
tesla-motors.0 | 2020-05-18 00:01:19.180 | warn | (12141) Invalid answer from Vehicle request. Error: Unauthorized

`

**Comment by ChrisPrefect** [comment]
To test the issue, you can change the password of you Tesla account. All current tokens will get invalidated immediately. Even using the same password as before works.

**Comment by StefanRied** [comment]
Same here. The adapter was still showing "green", but it did not work. 
Why can't the adapter refresh automatically every month?

BTW. I love the adapter. It is absolutely great, even with the shortcomings. Please keep the great work on.

**Comment by dbweb-ch** [comment]
There was a bug with refreshing on setting the next Refresh Date, this is fixed with the lastest commit. However I saw some strange behave when having invalid tokens, the api still responded the car state and didn't response with a "unauthorized" message, will have to investigate further. At least the refresh should now work properly.

**Comment by StefanRied** [comment]
I had an outdated token issues again last week with the current version. Just to let you know. Thanks for further investigation.

**Comment by dbweb-ch** [comment]
I hope this is closed now, please write another issue if not
