### ISSUE TITLE
Writing a data point after wake-up

### ISSUE THREAD

**Issue by mifricke** [dbweb-ch/ioBroker.tesla-motors#23]
Hi!

I've noticed several times that it doesn't always wake up reliably before a data point is written. 

If I change e.g. the target SoC to start a charging process, the data point is reset to the old value after some time (about 5-10 seconds). A new try is successful. This always seems to happen when the vehicle has slept.

Bug or feature? ;-)

**Comment by dbweb-ch** [comment]
Bug, I see the same issue, but did not yet have time to fix it. Will look into this soon.
