### ISSUE TITLE
Proactively prevent repetitive car wakeup when tesla-motors adapter misbehaves

### ISSUE THREAD

**Issue by jensb** [dbweb-ch/ioBroker.tesla-motors#24]
We had a problem recently with iobroker where the tesla-motors adapter kept exiting with error 156. This seems now fixed, but one consequence of this was that the adapter kept restarting and upon each restart, requested the "initial" full vehicle data - which prevented our car from going to sleep and thus wasted about 10kWh of energy over a week.
Is it possible to let tesla-motors keep a persistent record of the time of the last full vehicle data request and if this is too recent, do not even request it upon restart, but instead just request basic data which does not wake the vehicle up? This would avoid these kind of scenarios.
Thank you!

**Comment by dbweb-ch** [comment]
Yes, good idea, will include this into the next release.

**Comment by dbweb-ch** [comment]
Should be fixed in 0.5.4
