### ISSUE TITLE
charger_power with wrong unit (W instead of kW)

### ISSUE THREAD

**Issue by lobomau76** [dbweb-ch/ioBroker.tesla-motors#27]
The unit of charger_power is in W, but the value corresponds to kW.
The other problem is that the number is shown as  whole number only without decimals.
Here are some examples:
![image](https://user-images.githubusercontent.com/35029301/95435242-9fecda00-0952-11eb-904b-bc0dd01d4ccf.png)

**Comment by dbweb-ch** [comment]
The Unit is already fixed in the project, it will be included in the next release. If you need it, install the adapter via github.
The value you see is the value I get from the Car, if there is no decimals, the car doesn't report any decimals.
