### ISSUE TITLE
Start of trip not noticed when in "wait to let car go to sleep" phase

### ISSUE THREAD

**Issue by jensb** [dbweb-ch/ioBroker.tesla-motors#28]
When the adapter is waiting to let the car sleep (25 minutes I think), and *during this time* somebody gets in and starts a trip, this trip is ignored and not recorded. This is understandable, but unfortunate.

Is there a way to let the adapter know whether the car is really idle, or whether it should start recording data because a trip has been started or is about to start?

**Comment by dbweb-ch** [comment]
Unfortunately this is not possible. The car keeps the state "awake" in this time. Asking more information (like speed or anything else that needs a real connection to the car) will reset the car timer and it will never go to sleep.

**Comment by jensb** [comment]
Hm. Bummer.
Can we instead somehow reset the ioBroker timer? Because if there is a way to do this using an API I can add a bookmark in the in-car browser which I can just call when starting a trip, to trigger ioBroker to start recording. Just an idea ...

**Comment by dbweb-ch** [comment]
The system observes the state of shift, speed and climate to determine if someone is using the car. It will not go to sleep if one of those is set. So when you are in the car, you just need to "trigger" a refresh of data.
Set the state command.standby to true will trigger a refresh of all Data and should prevent it from waiting.
