### ISSUE TITLE
Warning after updating to js-controller 3.2.7

### ISSUE THREAD

**Issue by xengosam** [dbweb-ch/ioBroker.tesla-motors#37]
State "tesla-motors.0.info.connection" has no existing object, this might lead to an error in future versions

Regards,
xengosam

**Comment by lobomau76** [comment]
Yes, this warning I have for a long time now. My ioBroker is running with 3.2.16 at the moment.
`2021-02-17 09:55:15.754 - warn: tesla-motors.0 (1323) State "tesla-motors.0.info.connection" has no existing object, this might lead to an error in future versions`

Thank you for the adapter. It is working fine without errors!

**Comment by dbweb-ch** [comment]
fixed
