### ISSUE TITLE
Could not retrieve token, Error from Tesla: endpoint_deprecated:_please_update_your_app.

### ISSUE THREAD

**Issue by ChrisPrefect** [dbweb-ch/ioBroker.tesla-motors#40]
I can't get a new token. The adapter is installed in the latest version 0.3.1.

This seems like the app needs to be updated? Did Tesla really change the API again?

Thanks!
Chris

**Comment by ChrisPrefect** [comment]
I think this is the explanation: https://support.teslafi.com/en/communities/1/topics/16979-tesla-v3-api-tokens

Are you planning to upgrade the adapter? That would be great :-D

**Comment by dbweb-ch** [comment]
It seems they changed it, yes. As I am based on https://github.com/mseminatore/TeslaJS I need to wait until it gets updated, the good thing is that there is already a active pull request waiting for that case. As soon as this gets approved I will investigate the changes I have to make for this to work. Hope that this happens soon as you already logged out and others will follow.

**Comment by dbweb-ch** [comment]
Should be ok now.
