### ISSUE TITLE
Integration der Tesla Powerwall

### ISSUE THREAD

**Issue by funcarv3r** [dbweb-ch/ioBroker.tesla-motors#41]
Ist es möglich die Tesla Powerwall zu integrieren? Die API sollte ähnlich sein. 

Es gibt bereits eine Doku dazu:
https://github.com/vloschiavo/powerwall2

**Comment by dbweb-ch** [comment]
Der Adapter basiert auf https://www.npmjs.com/package/teslajs , leider ist dort die Powerwall nicht integriert, so ist eine Integration in den Adapter unwahrscheinlich. Es wäre aber eh besser, dafür einen separaten Adapter zu haben, hab aber aktuell keine Zeit das zu integrieren... und mir fehlt auch die Powerwall dazu.
