### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by souhl** [dbweb-ch/ioBroker.tesla-motors#45]
Hi,

do you support 2FA to login?
Getting issues when logging in and just want to double check if 2FA is supported at all.
Didn't information on this in the text.

Thanks
Sascha

**Comment by dbweb-ch** [comment]
Tesla changed its authentication, I am actually investigating what I need to change to make 2FA working. You can try but I assume it does not work currently.

**Comment by souhl** [comment]
Tested it, not working. TeslaJS is supporting it. But you need to add a possibility to provide the additional code for the authentication.

```
var tjs = require('teslajs');

    var username = "<your MyTesla email>";
    var password = "<your MyTesla password>";
    var mfaPassCode = "<your MFA passcode, if applicable>";

    tjs.login({
        username: username,
        password: password,
        mfaPassCode: mfaPassCode
    }, function(err, result) {
        if (result.error) {
          console.log(JSON.stringify(result.error));
          process.exit(1);
        }

        var token = JSON.stringify(result.authToken);

        if (token)
            console.log("Login Succesful!");
    });
```

**Comment by mischoe** [comment]
Any movement on this topic? The adapter is useless at the moment, as it is not able to retrieve a token...without 2FA

**Comment by dbweb-ch** [comment]
Where do you get the mfa-Passcode from?

**Comment by mischoe** [comment]
I use Autry on my Phone for getting Passcodes for MFA. Teslalogger had the same issue with MFA and Teslas changed  authentication. They are working again - when will this Biobroker plugin?

**Comment by dbweb-ch** [comment]
Does someone has any chance to login with MFA with teslajs? I tried their example "login.js" with my credentials and 2fa, and the login-request just gets stuck without any answer. I've implemented the MFA and wanted to test, and it does not work at all....

**Comment by mischoe** [comment]
I would try, but can't install 👍 
 ERR! code E404
npm 
ERR! 404 Not Found - GET https://github.com/dbweb-ch/ioBroker.tesla-motors/tree/AuthenticationWithMFACode/tarball/bffc9b1fe60e722d4f0afa3513cbbbe2cbde4657npm ERR! 404 npm ERR! 404  'https://github.com/dbweb-ch/ioBroker.tesla-motors/tree/AuthenticationWithMFACode/tarball/bffc9b1fe60e722d4f0afa3513cbbbe2cbde4657' is not in the npm registry.npm ERR! 404 Your package name is not valid, because npm ERR! 404  1. name can only contain URL-friendly charactersnpm ERR! 404  2. name can no longer contain capital lettersnpm ERR! 404 npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by dbweb-ch** [comment]
You need to install it over the "cat"-Symbol in io-Broker.

**Comment by mischoe** [comment]
That is exactly what I did...

**Comment by dbweb-ch** [comment]
You need to select the cat and then go to "beliebig" and insert the github repo. You tried "from github" which is acutally looking for an npm project, don't know why they name that tab "github"

**Comment by dbweb-ch** [comment]
I ussume you tried the link i've posted, but you need to take the "Clone"-Link which would be:
https://github.com/dbweb-ch/ioBroker.tesla-motors/tarball/AuthenticationWithMFACode

Btw. I've done an update on this, it might work better now.

**Comment by kaip2503** [comment]
Habe es gerade mal installiert. Bei mir funktioniert es bisher.

**Comment by souhl** [comment]
Login ohne 2FA mag funktionieren... ohne geht leider nicht. Es fehlt ja noch die Option den Passcode einzugeben. Daher kann es ja nicht gehen. Stehe gerne für Tests zur Verfügung...
<img width="815" alt="Bildschirmfoto 2021-03-11 um 16 36 44" src="https://user-images.githubusercontent.com/5879835/110812901-4df50b00-8288-11eb-9490-1f9e769df71e.png">

**Comment by dbweb-ch** [comment]
Hi Souhl,

as said:
I assume you tried the link i've posted, but you need to take the "Clone"-Link which would be:
https://github.com/dbweb-ch/ioBroker.tesla-motors/tarball/AuthenticationWithMFACode

In this branch there is the possibility to enter the 2 FA authentication:
![image](https://user-images.githubusercontent.com/57174794/110814067-6154a600-8289-11eb-99e7-9422760e8be3.png)

**Comment by souhl** [comment]
Oh, yes! Working! Cool!

**Comment by dbweb-ch** [comment]
merged version to master and will release to npm in a few minutes. It will take 1 day until it is in the stable repo of iobroker.
