### ISSUE TITLE
Login information can't be saved and no token can be received

### ISSUE THREAD

**Issue by ChrisPrefect** [dbweb-ch/ioBroker.tesla-motors#46]
I removed the adapter and added a new instance of 0.3.2.

After entering my login information I was not able to save the info, the save-buttons are greyed out.

Only after clicking on "smart" and choosing something else and then back to smart, the buttons became blue.

But clicking on "save" just gives an error message: 

![image](https://user-images.githubusercontent.com/3579863/107340408-0844f700-6abe-11eb-8801-5823f9755ec4.png)

OK, so I click on get token, then I see this:

![image](https://user-images.githubusercontent.com/3579863/107340451-13982280-6abe-11eb-9d32-90239d47f181.png)

These two error messages block each other out. I can't save the information because I need a token first, but to get a token I need to save the information.

**Comment by dbweb-ch** [comment]
you don't need to save to get a token, but your adapter seems not to be started. Make sure the adapter is started before you click on "TOCKEN HOLEN".

**Comment by ChrisPrefect** [comment]
These checks should be removed. It should always be able to save, regardless if the adapter is started or not.

When I install the adapter, I want to configure it first and start it afterwards. It is not logical to start an adapter which will 100% fail to start because it doesn't even have any login information saved :-)

And the first dropdown (polling strategy) should not be checked if it is filled out. It should be possible to save after just entering the email and password.

Thanks a lot!
Chris

**Comment by dbweb-ch** [comment]
It has to be started:
To get a token, the request has to be sent by the server. To send a request, the adapter has to be started. So this "restriction" is by design.
The adapter is made to not fail to start even if there are no credentials. If it would, it would never have been worked so far.

**Comment by ChrisPrefect** [comment]
Yes, I understand, but it is confusing. I should be able to save all fields, even if the adapter is not started and/or some fields are not yet filled out.

**Comment by dbweb-ch** [comment]
yes, I understand. But as it does not make much sense to save the fields when you did not yet get a token, I've decided to put a message "adapter has to be started" when trying to save. Usually adapter is started after you installed it too.

**Comment by ChrisPrefect** [comment]
OK, could you add an adapter-start button right on the configuration page? Then you don't lose all the data you just entered. Or don't open the configuration page at all when the adapter is not started? Or start it automatically when you hit save?

**Comment by dbweb-ch** [comment]
Need to check if some of this is possible
