### ISSUE TITLE
add homelink support

### ISSUE THREAD

**Issue by and-web** [dbweb-ch/ioBroker.tesla-motors#49]
According to [1], there is a command for homelink support which is for garage door openers. Is there maybe a possibility to implement this feature in the adapter? I provide any help necessary, unfortunately my programming skills don't go beyond shell scripts. :-(

[1] https://tesla-api.timdorr.com/vehicle/commands/homelink

**Comment by dbweb-ch** [comment]
There is also a homelink function in teslajs, which I am using. Problem is that I will not be able to test this, but I can integrate it and hope it is going to work. There are some code remarks that it might only work if you have the Autopilot package.

**Comment by and-web** [comment]
That would be great. I would support testing it. I don't have FSD but the new EAP option (enhanced autopilot). It would be interesting to find out if this is sufficient.

**Comment by dbweb-ch** [comment]
I've tried to write this witout testing. Please install this version using following link:
https://github.com/dbweb-ch/ioBroker.tesla-motors/tarball/homelinkSupport
Please turn log level to debug and try it out.
Remember: Homelink does only work when car is close to where device sits (logically). You can see this by checking 'vehicle.homelink_nearby' and 'vehicle.homelink_device_count' (These states are also logged when log is on debug).
Looking forward to get the feedback needed from you.

**Comment by dbweb-ch** [comment]
@and-web  Did you try it out?

**Comment by and-web** [comment]
Sorry for the delay! Tested it, worked smoothly out of the box. Even better than expected, via App it's not possible to activate homelink about 20 meters away but using the iobroker adapter, it works even from that distance. From my point of view, the feature is ready to be published into the wild. Thank you so much! Video demo here: https://www.youtube.com/watch?v=HsllDdr5Kvc

**Comment by danimeierch** [comment]
Thank you for the information when the function is pushed into the wild... 👍

**Comment by dbweb-ch** [comment]
this should now appear in the latest repo. Attention: Latest is on Version 0.5, you will have to reenter credentials when installing this version.
