### ISSUE TITLE
please use decrypt from tools.js

### ISSUE THREAD

**Issue by GermanBluefox** [dbweb-ch/ioBroker.tesla-motors#6]
https://github.com/dbweb-ch/ioBroker.tesla-motors/blob/master/main.js#L902
Replace with 
```
const tools 	  = require(utils.controllerDir + '/lib/tools.js');
tools.decrypt('secret', '9876968687')
```

**Comment by dbweb-ch** [comment]
Done.
Is there also an official way how this could be used by index_m? Decrypt from tools.js while encrypted and decrypted by function in index_m doesn't look clean.

**Comment by GermanBluefox** [comment]
I understand, that this is not clear solution, and that the password should be sent only in one direction: from index.html to server and never back. 
But for now we have only this and we must to change it in the future.
