### ISSUE TITLE
Charge power change

### ISSUE THREAD

**Issue by danimeierch** [dbweb-ch/ioBroker.tesla-motors#60]
Hi! A brillant plugin, thanks a lot!! Just one thing. I'd like to change the charge power (ex. 24 A) with the plugin to another value. Is it possible to implement that? Thanks a lot! Best Regards, Daniel

**Comment by IT-Economy** [comment]
I don't think you can change the charge level over the Tesla API.

You need to add a Raspberry Pi to your Tesla wall box to do that remotely. 

https://www.matusz.ch/blog/2020/07/06/mit-der-tesla-wallbox-intelligent-laden/#:~:text=Alle%20zusammen%20nutzen%20das%20integrierte,steuern%20damit%20die%20untergeordnete%20Ladestelle.

**Comment by danimeierch** [comment]
Thank you for your answer. I just saw in the API that it isn't possible (yet). :-(
