### ISSUE TITLE
tesla-motors.0.command.seat_heater_rear_right has no existing object

### ISSUE THREAD

**Issue by DanielWeeber** [dbweb-ch/ioBroker.tesla-motors#63]
State "tesla-motors.0.command.seat_heater_rear_right" has no existing object, this might lead to an error in future versions

Gleiche mit "rear_left" und "rear_center"

**Comment by dbweb-ch** [comment]
Fixed

**Comment by DanielWeeber** [comment]
Leider war nach Update über Github alles bzgl. Authorization weg, auch sieht die Einstellungs-Seite seltsam aus, sodass ich nichts neues mehr eingeben kann



```


tesla-motors.0 | 2021-05-05 18:22:29.559 | warn | (30696) Could not retrieve Data from the Car! Response: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Authorization"]
-- | -- | -- | --
tesla-motors.0 | 2021-05-05 18:22:29.556 | warn | (30696) Invalid answer from Vehicle request. Error: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Authorization"]


```
<img width="2326" alt="Bildschirmfoto 2021-05-05 um 18 21 08" src="https://user-images.githubusercontent.com/2935130/117175037-aea74c80-adce-11eb-92c2-7bcc0ec8e1ea.png">

**Comment by dbweb-ch** [comment]
welche Version hattest du vorher? Authorisation ist weg, das ist "normal", siehe "release notes" zu 0.5.0. Aber ansonsten sollte es sauber klappen, tut es jedenfalls bei mir.

**Comment by dbweb-ch** [comment]
Sorry, konnte das ganze jetzt doch noch nachstellen. Bugfix ist auf github drauf, du kannst wieder auf Version 0.5.0 wenn du willst. Authentifizierung wirst du aber nochmals eingeben müssen beim upgrade.
