### ISSUE TITLE
undefined is not a valid state value

### ISSUE THREAD

**Issue by xengosam** [dbweb-ch/ioBroker.tesla-motors#70]
Hi,

after updating I get following messages that are spamming my log .. 

tesla-motors.0 | 2021-05-07 16:05:27.188 | info | (26991) undefined is not a valid state value for tesla-motors.0.vehicle.homelink_device_count

tesla-motors.0 | 2021-05-07 16:05:27.188 | info | (26991) undefined is not a valid state value for tesla-motors.0.vehicle.homelink_nearby

For your information, I do not have Homelink on my Tesla Model 3.

Thanks ,
xengosam

**Comment by dbweb-ch** [comment]
Thanks for the report. It seems that homelink-states do not exist when the car has no autopilot. I've made a hotfix for this and pushed it to the latest version on github, if you want you can update from there.

**Comment by xengosam** [comment]
Thanks for the fix! Everything works like expected.
