### ISSUE TITLE
has to be type "boolean" but received type "number"

### ISSUE THREAD

**Issue by lobomau76** [dbweb-ch/ioBroker.tesla-motors#76]
Following info appears with js-controller 3.3.10:
`

tesla-motors.0 | 2021-05-27 21:05:58.587 | info | (15277) State value to set for "tesla-motors.0.climateState.rear_passenger_window" has to be type "boolean" but received type "number"
-- | -- | -- | --
tesla-motors.0 | 2021-05-27 21:05:58.587 | info | (15277) State value to set for "tesla-motors.0.climateState.rear_driver_window" has to be type "boolean" but received type "number"
tesla-motors.0 | 2021-05-27 21:05:58.577 | info | (15277) State value to set for "tesla-motors.0.climateState.front_passenger_window" has to be type "boolean" but received type "number"
tesla-motors.0 | 2021-05-27 21:05:58.577 | info | (15277) State value to set for "tesla-motors.0.climateState.front_driver_window" has to be type "boolean" but received type "number"
tesla-motors.0 | 2021-05-27 21:05:58.521 | info | (15277) undefined is not a valid state value for id "tesla-motors.0.climateState.smart_preconditioning"
tesla-motors.0 | 2021-05-27 21:05:58.520 | info | (15277) undefined is not a valid state value for id "tesla-motors.0.command.steering_wheel_heater"
tesla-motors.0 | 2021-05-27 20:50:47.608 | info | (15277) State value to set for "tesla-motors.0.climateState.rear_passenger_window" has to be type "boolean" but received type "number"
tesla-motors.0 | 2021-05-27 20:50:47.608 | info | (15277) State value to set for "tesla-motors.0.climateState.rear_driver_window" has to be type "boolean" but received type "number"
tesla-motors.0 | 2021-05-27 20:50:47.606 | info | (15277) State value to set for "tesla-motors.0.climateState.front_passenger_window" has to be type "boolean" but received type "number"
tesla-motors.0 | 2021-05-27 20:50:47.606 | info | (15277) State value to set for "tesla-motors.0.climateState.front_driver_window" has to be type "boolean" but received type "number"
tesla-motors.0 | 2021-05-27 20:50:47.596 | info | (15277) undefined is not a valid state value for id "tesla-motors.0.climateState.smart_preconditioning"
tesla-motors.0 | 2021-05-27 20:50:47.595 | info | (15277) undefined is not a valid state value for id "tesla-motors.0.command.steering_wheel_heater"

`

**Comment by dbweb-ch** [comment]
This should already be fixed with latest version from github, which version do you have?

**Comment by lobomau76** [comment]
0.4.2 is installed.
In the 0.4.3 changelog was written nothing about this solution. I will try this out.

**Comment by lobomau76** [comment]
Now I have installed 0.5.1. It seems to run without to much logs.
