### ISSUE TITLE
Missing objects for sun roof

### ISSUE THREAD

**Issue by PanRe** [dbweb-ch/ioBroker.tesla-motors#93]
These two warnings pop up in the logs:
`(12078) State "tesla-motors.0.climateState.sun_roof_percent_open" has no existing object, this might lead to an error in future versions`
and
`(12078) State "tesla-motors.0.command.SunRoofVent" has no existing object, this might lead to an error in future versions`

**Comment by dbweb-ch** [comment]
fixed in https://github.com/dbweb-ch/ioBroker.tesla-motors/commit/b99a9ef6e98248453bf23c1f3583f1fb386692bb
